#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: #@ data.values.system_namespace
data:
  fluentd.conf: |
    # Inputs
    <source>
      @type forward
      tag forwarded.test
      port 24224
    </source>

    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      refresh_interval 1
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
      read_from_head true
    </source>

    <source>
      @type tail
      @id in_tail_ingressgateway_logs
      path /var/log/containers/istio-ingressgateway*istio-proxy*.log
      pos_file /var/log/fluentd-istio-ingressgateway.log.pos
      tag istio-ingressgateway
      refresh_interval 1
      <parse>
         @type json
         format json
         time_key time
         time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
      read_from_head true
    </source>

    # Filters
    <match kubernetes.var.log.containers.fluentd**>
      @type null
    </match>

    <filter istio-ingressgateway>
      @type parser
      format json
      key_name log
    </filter>

    <filter istio-ingressgateway>
      @type record_transformer
      enable_ruby
      <record>
        app_id ${record["app_id"]}
        instance_id 0
        log ${record.to_json}
        source_type RTR
        structured_data \[tags@47450 source_type="RTR"\]
      </record>
    </filter>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby
      <record>
        app_id ${record.dig("kubernetes", "labels", "cloudfoundry_org/app_guid")}
        instance_id ${record.dig("kubernetes", "pod_id")}
        structured_data \[tags@47450 source_type="${record.dig("kubernetes", "labels", "cloudfoundry_org/source_type")}"\]
      </record>
    </filter>

    <filter forwarded.**>
      @type record_transformer
      enable_ruby
      <record>
        structured_data \[tags@47450 source_type="${record.dig("source_type")}"\]
      </record>
    </filter>

    <filter **>
      @type grep
      <regexp>
        key $.app_id
        pattern /.+/
      </regexp>
    </filter>

    <match **>
      @type syslog_rfc5424
      host log-cache-syslog
      port 8082
      transport tls
      trusted_ca_path /ca/tls.crt
      <format>
        @type syslog_rfc5424
        proc_id_field instance_id
        app_name_field app_id
        structured_data_field structured_data
      </format>

      <buffer>
        @type memory
        flush_mode immediate
      </buffer>
    </match>
